### ISSUE TITLE
Elemental ui extension 1.10 should not be installable in rancher 2.7.1

### ISSUE THREAD

**Issue by juadk** [rancher/elemental-ui#102]
As discussed yesterday with @aalves08, I was able to install elemental-ui extension 1.1.0 in rancher 2.7.1:

```
helm upgrade --install rancher rancher-latest/rancher --namespace cattle-system --create-namespace --set replicas=1 --set hostname=rancher.138.68.110.84.sslip.io --set bootstrapPassword=password --version 2.7.1
```
`image: rancher/ui-plugin-operator:v0.1.0`

![image](https://user-images.githubusercontent.com/6025636/235848774-3f09e716-ca9b-416b-a0e9-5cad73efd6a9.png)

![image](https://user-images.githubusercontent.com/6025636/235848858-370630cf-8502-43d3-b9e1-77db9510c26b.png)

![image](https://user-images.githubusercontent.com/6025636/235848956-4c00450b-3988-4b41-82cf-7fd4c7a845e2.png)

![image](https://user-images.githubusercontent.com/6025636/235849081-ae52716a-8cbd-44af-b902-3d22864e7377.png)

And things like elemental-icon are broken:
![image](https://user-images.githubusercontent.com/6025636/235849511-81ddc2a8-2b26-4536-84c0-dba208c995e3.png)

**Comment by aalves08** [comment]
What I can do is limit the rancher version for this extension, with the side effect that it won't even show on the extensions screen that there's a 1.1.0 available for upgrade. Shall I do that?

**Comment by aalves08** [comment]
The mechanism of https://github.com/rancher/dashboard/issues/9132 should help with this

**Comment by aalves08** [comment]
Closing in favor of https://github.com/rancher/elemental-ui/issues/225
