### ISSUE TITLE
Update managed OS versions for OS upgrade

### ISSUE THREAD

**Issue by aalves08** [rancher/elemental-ui#104]
Based of: https://github.com/rancher/elemental-operator/pull/435

**Comment by aalves08** [comment]
This should filter out the ISO's from the list of OS versions available @juadk

**Comment by juadk** [comment]
Looks good, I can see the new type column with iso and container:
![image](https://github.com/rancher/elemental-ui/assets/6025636/500db6d8-854f-4541-862f-3f4ca4d8cd06)

And only ISO type is usable when you want to build the ISO:
![image](https://github.com/rancher/elemental-ui/assets/6025636/56c9639f-c431-4c28-8b73-946165e2a196)
