### ISSUE TITLE
Update build ISO to use the OS versions resource instead of hardcoded list

### ISSUE THREAD

**Issue by aalves08** [rancher/elemental-ui#105]
based of: https://github.com/rancher/elemental-operator/pull/435

**Comment by kkaempf** [comment]
@aalves08 we would need this by end of week, if possible

**Comment by aalves08** [comment]
Should be taken care of @kkaempf . PR up for review:
https://github.com/rancher/elemental-ui/pull/111

**Comment by juadk** [comment]
I will check it but not sure I will be able to do it before next Monday, bank holiday tomorrow and day off on Friday in France.
