### ISSUE TITLE
When provisioning an Elemental cluster, the `Provider` column reads as `Elemental Cluster` instead of just `Elemental`

### ISSUE THREAD

**Issue by markusewalker** [rancher/elemental-ui#11]
**Setup**
- Rancher version: `v2.6.8`
- Browser type & version: Chrome

**Describe the bug**

When deploying an Elemental cluster, the display name in the `Provider column` is shown as `Elemental Cluster` as shown below:

![image](https://user-images.githubusercontent.com/52591819/189202254-9a0ace59-a1a9-4ad0-97c7-6dd117d51ea3.png)

We should have the name be just `Elemental`. When provisioning from other baremetal providers such as Harvester, we list it out as just `Harvester` and not `Harvester Cluster`. It is redundant to add cluster as we're already in Cluster Management, so a customer will already understand.

Additionally, Cluster Management has this same problem:

![image](https://user-images.githubusercontent.com/52591819/189207917-9adf303f-b492-4447-b22d-89cee7f3d4c8.png)

This should read as just `Elemental` as well.

**To Reproduce**

1. Setup Rancher and navigate to OS Management.
2. Create a machine registration and a machine inventory, according to your specifications.
3. Once done, head to OS Management > Dashboard > Create Elemental Cluster.
4. Provision an Elemental cluster and note that the `Provider` name is `Elemental Cluster`.
5. Navigate to Cluster Management > Create.
6. Toggle to RKE2/K3s and note that you see `Elemental Cluster` instead of just `Elemental`.

**Result**
The `Provider` column shows `Elemental Cluster`.

**Expected Result**

The `Provider` column should show `Elemental`.

**Comment by juadk** [comment]
All good with the latest release (0.1.1):
![image](https://user-images.githubusercontent.com/6025636/201103447-8648cafb-ee97-4bc5-b0bb-469fddab03ff.png)
![image](https://user-images.githubusercontent.com/6025636/201103532-46069e15-f4dc-456d-8572-8b3a409d8123.png)

The issue can be closed.
