### ISSUE TITLE
Issue with OS version name when building SeedImage

### ISSUE THREAD

**Issue by juadk** [rancher/elemental-ui#118]
With the default embedded channel `registry.opensuse.org/isv/rancher/elemental/dev/teal53/15.4/rancher/elemental-teal-channel/5.3:latest` , I see two OS version with the same name when I want to build ISO:

![image](https://github.com/rancher/elemental-ui/assets/6025636/3318138c-5b6a-4d88-a560-fc02e1367968)

and both point to `registry.opensuse.org/isv/rancher/elemental/dev/teal53/15.4/rancher/elemental-teal-iso/5.3:latest` as baseImage.

David is aware and asked me to open that issue.

**Comment by aalves08** [comment]
Hi @juadk .

That list of available ISO's now comes from the OS versions type `iso`:

https://github.com/rancher/elemental-ui/blob/main/pkg/elemental/components/BuildIso.vue#L51-L58
which comes from 
https://github.com/rancher/elemental-ui/blob/main/pkg/elemental/components/BuildIso.vue#L31-L33

the [code](https://github.com/rancher/elemental-ui/blob/main/pkg/elemental/components/BuildIso.vue#L51-L58) get's all the information from the OS versions (label and value), for which if you have a duplicated label, it means that you are importing stuff from the OS version channels that duplicate these. Can you confirm that's the scenario?

**Comment by juadk** [comment]
yes, let me try to explain it better, ok for the double name but:
![image](https://github.com/rancher/elemental-ui/assets/6025636/0ec3e060-0732-4848-842c-0ba167209322)
`latest-dev` points to:
```
    upgradeImage: >-
      registry.opensuse.org/isv/rancher/elemental/dev/teal53/15.4/rancher/elemental-teal/5.3:latest
```
and `v1.1.4` points to:
`upgradeImage: register.suse.com/rancher/elemental-teal/5.3:1.1.4`

But when I create SeedImage with both of them, I see the same `baseImage` inside:
```
    baseImage: >-
    registry.opensuse.org/isv/rancher/elemental/dev/teal53/15.4/rancher/elemental-teal-iso/5.3:latest
```

If I'm not mistaken, `v1.1.4` should point to the stable iso and not the dev one, @davidcassany could you confirm please?

**Comment by davidcassany** [comment]
The contents of the channel are:

```json
[
  {
    "metadata": {
      "name": "latest-dev"
    },
    "spec": {
      "version": "latest-dev",
      "type": "container",
      "metadata": {
        "upgradeImage": "%%IMG_REPO%%/rancher/elemental-teal/5.3:latest",
        "displayName": "Elemental Teal OS"
      }
    }
  },
  {
    "metadata": {
      "name": "latest-dev-iso"
    },
    "spec": {
      "version": "latest-dev",
      "type": "iso",
      "metadata": {
        "uri": "%%IMG_REPO%%/rancher/elemental-teal-iso/5.3:latest",
        "displayName": "Elemental Teal ISO x86_64"
      }
    }
  },
  {
    "metadata": {
      "name": "v1.1.4"
    },
    "spec": {
      "version": "v1.1.4",
      "type": "container",
      "metadata": {
        "upgradeImage": "register.suse.com/rancher/elemental-teal/5.3:1.1.4",
        "displayName": "Elemental Teal OS"
      }
    }
  },
  {
    "metadata": {
      "name": "v1.1.4-iso"
    },
    "spec": {
      "version": "v1.1.4",
      "type": "iso",
      "metadata": {
        "uri": "https://updates.suse.com/SUSE/Updates/ElementalTeal/5.3/x86_64/update/iso/elemental-teal.x86_64-1.1.4-Build3.2.30.iso",
        "displayName": "Elemental Teal ISO x86_64"
      }
    }
  }
]
```

So four managedOSVersions two of them being contianers and two being ISOs. The list in the OS versions seams to be fine, the list of the ISOs however seams to be wrong. I'd expect to see in the list the following items:

`Elemental Teal ISO x86_64 v1.1.4` (points to `.../update/iso/elemental-teal.x86_64-1.1.4-Build3.2.30.iso`) and `Elemental Teal ISO x86_64 latest-dev` (points to `.../rancher/elemental-teal-iso/5.3:latest`).

So according to @juadk analysis it looks like there is something odd with the ISOs list, like if one overwrites the other. @aalves08 does the channel you get match the above list?

**Comment by aalves08** [comment]
I believe, for same labels, it just get's the endpoint of the first option, even though you selected the second, because they are not unique.
With the memoization of the seedImage that I am currently working on ([PR here](https://github.com/rancher/elemental-ui/pull/113)) duplicate labels is going to become a problem.

**Comment by juadk** [comment]
I was able to build ISO from dev and from stable in the UI!
![image](https://github.com/rancher/elemental-ui/assets/6025636/50a535a9-87ad-4fb4-8c1c-eaa9c6c62f24)
_**side note: I manually edited the display name for the dev version**_

I booted one of my NUC with stable ISO and I got:
```
IMAGE_REPO="registry.suse.com/rancher/elemental-teal/5.3"
IMAGE_TAG="1.1.4-3.2.30"
IMAGE="registry.suse.com/rancher/elemental-teal/5.3:1.1.4-3.2.30"
```
And another NUC with dev ISO:
```
IMAGE_REPO="registry.opensuse.org/isv/rancher/elemental/dev/teal53/15.4/rancher/elemental-teal/5.3"
IMAGE_TAG="1.1.5-200.1"
IMAGE="registry.opensuse.org/isv/rancher/elemental/dev/teal53/15.4/rancher/elemental-teal/5.3:1.1.5-200.1"
```

The last thing is to use a different display name but that one is in the backend. So I would say all good from UI point of view.

PS: I will have to update our automation to use it instead of building dev ISO with SeedImage directly.
