### ISSUE TITLE
Revert filtering of ManagedOSversion list

### ISSUE THREAD

**Issue by aalves08** [rancher/elemental-ui#120]
We had implemented the filtering of the ManagedOSversion list, where we filter out the iso type resources. They are to be featured again on the list view and a new column "Type" will be added to help users further distinguish between type "iso" and "container"

**Comment by juadk** [comment]
Tested successfully!
![image.png](https://zube.io/files/rancher/49019a9e16faa70d1f11d6b7243fec88-image.png)
