### ISSUE TITLE
Change elemental.cattle.io to Elemental in menu

### ISSUE THREAD

**Issue by ldevulder** [rancher/elemental-ui#121]
With the UI plugin installed and in `Local` cluster we can see `elemental.cattle.io`, it could be better to set this to `Elemental` when the plugin is installed.

![elemental_menu](https://github.com/rancher/elemental-ui/assets/25102165/07135005-d6a3-4b2e-b8a4-e9209c7367fb)

**Comment by juadk** [comment]
All good with latest dev 1.3.0:
![image](https://github.com/rancher/elemental-ui/assets/6025636/470bade5-5d4c-4d73-accd-c9fa92679b54)
