### ISSUE TITLE
Machine registration: cloud-config not shown after using Read From File button

### ISSUE THREAD

**Issue by juadk** [rancher/elemental-ui#122]
When you create a machine registration, the cloud-config section is empty when you use the Read From File button.

![image](https://github.com/rancher/elemental-ui/assets/6025636/d8675ab2-53bb-474c-b9b4-9f64765afbff)
Select your file

![image](https://github.com/rancher/elemental-ui/assets/6025636/f9b95bbf-6267-4f3f-b2f8-b658f02c8a6e)

Then, click on `Create`:
And the cloud section is empty
![image](https://github.com/rancher/elemental-ui/assets/6025636/67acf292-6102-4847-9fc5-b43ce1a02667)

I just checked our e2e test code and it's not tested yet, we only use `Read From File` button to import machine inventory. I will create a ticket to automate that test.

**Comment by aalves08** [comment]
Hi @juadk . I've just done a few tests and if you pass a valid cloud config, it works perfectly. If you pass invalid data, it gets sent to the server, but the backend strips it, meaning that it does some validation and assumes that it's not valid.

Looking at your screenshots, you tried to do that with "invalid" data on the cloud config.

**Comment by aalves08** [comment]
You can just use whatever is inside "cloud config", like the structure you can see on the registration endpoint:

![Screenshot 2023-06-12 at 16 48 28](https://github.com/rancher/elemental-ui/assets/97888974/fa5a685c-6161-427d-b2f4-28619adfe8ed)

**Comment by juadk** [comment]
You are right, my mistake, all good if I use only what is inside `config`, sorry for the noise.

**Comment by aalves08** [comment]
No worries mate. 🙏
