### ISSUE TITLE
Concatenate display label with version on Select for ISO's on build ISO feature

### ISSUE THREAD

**Issue by aalves08** [rancher/elemental-ui#123]
Currently we are only displaying the `spec.metadata.displayName` as a label for an ISO in the Select input on build ISO feature.
We should concatenate it with `spec.version` so that is meaningful to the user

![Screenshot 2023-06-15 at 17.26.41.png](https://zube.io/files/rancher/58e8fde399d5dbf46603b9a1d6d9c550-screenshot-2023-06-15-at-17-26-41.png)

**Comment by juadk** [comment]
![Image](https://github.com/rancher/elemental-operator/assets/6025636/951a7862-b29c-43ba-a4cb-880df5a48909)


Manual tests ok, I built ISO with both entries and:
system installed from dev:
```
CPE_NAME="cpe:/o:suse:sle-micro-rancher:5.3"
IMAGE_REPO="registry.opensuse.org/isv/rancher/elemental/dev/teal53/15.4/rancher/elemental-teal/5.3"
IMAGE_TAG="1.1.5-200.1"
IMAGE="registry.opensuse.org/isv/rancher/elemental/dev/teal53/15.4/rancher/elemental-teal/5.3:1.1.5-200.1"
```
system installed from stable:
```
CPE_NAME="cpe:/o:suse:sle-micro-rancher:5.3"
IMAGE_REPO="registry.suse.com/rancher/elemental-teal/5.3"
IMAGE_TAG="1.1.4-3.2.30"
IMAGE="registry.suse.com/rancher/elemental-teal/5.3:1.1.4-3.2.30"
```

I have triggered automated tests to check regressions, still in progress, will update the ticket later.
