### ISSUE TITLE
Fix Elemental Dashboard icon on dark mode

### ISSUE THREAD

**Issue by aalves08** [rancher/elemental-ui#130]
- Fix Elemental Dashboard icon on dark mode

![Screenshot 2023-07-17 at 12 14 18](https://github.com/rancher/elemental-ui/assets/97888974/3c26862d-c643-40dc-a5a5-dc97fe03ad4d)

**Comment by juadk** [comment]
All good with elemental-ui 1.3.0:
![image](https://github.com/rancher/elemental-ui/assets/6025636/a806124c-a10c-48f9-a514-f29d6db59450)
