### ISSUE TITLE
Make the UI extension to install the charts from the market place

### ISSUE THREAD

**Issue by davidcassany** [rancher/elemental-ui#139]
The idea is to make elemental installation a single step from the UI perspective.

**Comment by juadk** [comment]
Tested with latest elemental-ui dev extension (1.3.0):
If the operator is not already installed, elemental-ui will let you know and there is a button to install it directly without going through the Marketplace:

1. 
![image](https://github.com/rancher/elemental-ui/assets/6025636/1a7d8b95-e286-4247-808d-8b2229138163)

2. 
![image](https://github.com/rancher/elemental-ui/assets/6025636/7e35b8d4-768e-4525-b6d4-f21b967986d7)

3. 
![image](https://github.com/rancher/elemental-ui/assets/6025636/1d299679-e456-406a-94dc-a3e12473f976)

4. 
![image](https://github.com/rancher/elemental-ui/assets/6025636/d9f0ee04-b060-41c4-b392-86e62abe081d)

All good to me, I will add this to the automated test.
