### ISSUE TITLE
Revert machine count update

### ISSUE THREAD

**Issue by aalves08** [rancher/elemental-ui#162]
Based on customer feedback we will revert changes done on machine count update done on https://github.com/rancher/elemental-ui/pull/47/files#diff-b1fa4d5afb43fb7fa58b30c56ebf3632e82c945c4f93a97973f65245e64decae

**Comment by juadk** [comment]
Tested successfully with elemental ui extension `1.3-rc`:

<img width="1597" alt="Screenshot 2024-03-19 at 10 14 18" src="https://github.com/rancher/elemental-ui/assets/6025636/a842aab4-827d-4d8c-9a3d-5d2c239d10c1">

The machine count stays at 1 even with 2 machine inventory matches.
