### ISSUE TITLE
Create feature versioning mechanism to handle impact of elemental-operator changes in the UI

### ISSUE THREAD

**Issue by aalves08** [rancher/elemental-ui#170]
With the changes coming from https://github.com/rancher/elemental-operator/issues/691, a mechanism will need to be created to handle feature versioning in the UI dependent on the elemental-operator version.

Two immediate areas of impact are:
- Raw disk images can only be built using the UI starting from elemental-operator v1.5.x
- The machine registration defaults in latest UI RC are only supported for v1.5.x and onwards. Basically the snapshotter related defaults. On previous versions the defaults should not include the snapshotter field.

**Comment by juadk** [comment]
I just found this issue https://github.com/rancher/elemental-ui/issues/175

**Comment by juadk** [comment]
The issue mentioned above is fixed so all good to me.
