### ISSUE TITLE
Bug with OS versions in Build media not being populated when refresh/reload

### ISSUE THREAD

**Issue by aalves08** [rancher/elemental-ui#172]
Fix bug with OS versions in `Build media` not being populated when refresh/reload

![Screenshot 2024-04-09 at 12 15 42](https://github.com/rancher/elemental-ui/assets/97888974/c6d378e5-1e9e-47b1-9389-7b278b4dabc4)

**Comment by juadk** [comment]
Tested successfully with latest ui dev version (rc4)
