### ISSUE TITLE
UI version v1.3 is installable in Rancher v2.7.x

### ISSUE THREAD

**Issue by davidcassany** [rancher/elemental-ui#176]
UI version v1.3 includes an install button for the elemental-operator app from the marketplace. Elemental operator was added to the marketplace starting from Rancher v2.8, hence when the UI runs on Rancher v2.7.x it should either not allow to install version v1.3 or eventually hide this installation button.

The problem is that installing Elemental UI extension v1.3 on Rancher v2.7 leads to a very confusing and misleading behavior. If you click the install button it never complains and it actually does something (logs even say it succeeded). The result is no app is installed and a weird artifact appears in the Extensions pane, see the screenshot.
![image](https://github.com/rancher/elemental-ui/assets/6428768/744d1060-15f1-45e3-8067-65c2b73a175c)

Found and reported by @stalin4suse

**Comment by aalves08** [comment]
Closing in favor of https://github.com/rancher/elemental-ui/issues/225
