### ISSUE TITLE
RKE2 is not shown when provisioning an Elemental cluster; only K3s is shown

### ISSUE THREAD

**Issue by markusewalker** [rancher/elemental-ui#18]
**Setup**
- Rancher version: `v2.7.0-rc1`
- Browser type & version: Chrome

**Describe the bug**
When going to provision an Elemental cluster, once you toggle the RKE2/k3s button in Cluster Management > Create, you are directed to fill out details to provision the cluster. This is expected, but when you look at the K8s version dropdown, you only see K3s and not RKE2.

This is incorrect, there needs to be RKE2 along with K3s. RKE2 is already GA within the Rancher product, K3s is still in `Tech Preview`. As such, this needs to be properly addressed and more emphasis needs to be placed on RKE2.

**To Reproduce**

1. Setup Rancher and login to the UI.
2. Navigate to Cluster Management > RKE2/K3s > Elemental Cluster.
3. Note that in the K8s version dropdown, only K3s is shown and not RKE2.

**Result**
RKE2 is not shown in the K8s version dropdown.

**Expected Result**

RKE2 needs to be shown in the K8s version dropdown as it is already GA in Rancher.

**Comment by juadk** [comment]
Successfully tested with elemental-ui 0.1.1
