### ISSUE TITLE
Support channel automatic deletion option

### ISSUE THREAD

**Issue by anmazzotti** [rancher/elemental-ui#189]
A new `ManagedOSVersionChannel` option has been added to automatically delete deprecated OS versions that are no longer included in the channel.

This can be enabled with `ManagedOSVersionChannel.spec.deleteNoLongerInSyncVersions` boolean flag.
Default value is `false`. 
See [reference](https://elemental.docs.rancher.com/next/managedosversionchannel-reference/#managedosversionchannelspec-reference).

This option should be added as selectable when creating a new channel on the UI.

**Comment by juadk** [comment]
Tested with rancher 2.9.0 / operator 1.6.3 / elemental UI 2.0.0-rc1:

![Image](https://github.com/user-attachments/assets/47d7d02a-4aa2-41c3-8cf4-dfce13d63cc2)
