### ISSUE TITLE
Unable to access `OS Management` as a restricted admin user

### ISSUE THREAD

**Issue by markusewalker** [rancher/elemental-ui#19]
**Setup**
- Rancher version: `v2.7.0-rc1`
- Browser type & version: Chrome

**Describe the bug**

When logged into Rancher as a restricted administrator, I am unable to access `OS Management`. This should not be the case as both an administrator user, restricted or not, should be able to access this to perform the expected operations when working with Elemental.

**To Reproduce**

1. Setup Rancher with the elemental operator and login to the UI.
2. Create a restricted administrator and login as that user.
3. Attempt to access `OS Management`; you are unable to.

**Result**
Unable to access `OS Management` as a restricted admin.

**Expected Result**

I should be able to access `OS Management` as a restricted admin.

**Comment by agracey** [comment]
We added a GlobalRole called "Elemental Admin" in the operator helm chart. Are you able to add that role to your user?

**Comment by agracey** [comment]
For reference: https://github.com/rancher/elemental-operator/blob/main/chart/templates/globalrole.yaml

**Comment by aalves08** [comment]
Just tested with a standard user + Elemental admin role and was able to create all of the resources needed for elemental

**Comment by juadk** [comment]
Today I was able to deploy k3s/RKE2 elemental node either as admin and user granted with elemental-administrator role!
This one can be closed as well.
