### ISSUE TITLE
Remove deprecated nuxt-link from codebase

### ISSUE THREAD

**Issue by aalves08** [rancher/elemental-ui#197]
Remove deprecated `nuxt-link` from codebase. Use `router-link` instead.

Only affects these buttons on Dashboard view:

![Image](https://github.com/user-attachments/assets/bab0c652-bf79-4c1b-841e-ccd31dd83a20)

**Comment by juadk** [comment]
Tested with rancher 2.9.0 / operator 1.6.3 / elemental UI 2.0.0-rc1:
Automated tests are able to select and click the buttons, all good.
