### ISSUE TITLE
Elemental UI extension cannot be installed in rancher 2.9-head and rancher 2.8-head anymore

### ISSUE THREAD

**Issue by juadk** [rancher/elemental-ui#202]
This issue was spotted in the CI and I can reproduce it locally:

![image](https://github.com/user-attachments/assets/50decb32-52a1-4ae8-9c56-5234fd423d41)

The install button in the elemental card does not appear anymore.

## Env
<img src="https://github.com/user-attachments/assets/0b383b8f-a554-4f97-b690-10f1e1f05ee8" width="500">

**Comment by juadk** [comment]
The bug is fixed for `rancher2.9-head` but I hit the same one with `rancher2.8-head`

**Comment by aalves08** [comment]
@richard-cox, @juadk  will take care of manual testing the backport for 2.8: https://github.com/rancher/dashboard/pull/11509

FYI @gaktive

**Comment by juadk** [comment]
I tested the fix for `2.8-head` and `2.9-head` and all worked as expected.
We can close this issue.
