### ISSUE TITLE
Add copy to build media to warn users not to change page + add download btn seed image

### ISSUE THREAD

**Issue by aalves08** [rancher/elemental-ui#204]
Add copy to build media to warn users not to change page + add download button to seed image list view

**Comment by juadk** [comment]
Tested with rancher 2.9.0 / operator 1.6.3 / elemental UI 2.0.0-rc1:
![Image](https://github.com/user-attachments/assets/a059d866-50d8-4304-b153-7dd139a5695e)


![Image](https://github.com/user-attachments/assets/8efb78c6-528c-4c7b-a3d5-42740cd124e8)
