### ISSUE TITLE
Add copy to update group target clusters to warn users about clusters that are already targeted won't show up

### ISSUE THREAD

**Issue by aalves08** [rancher/elemental-ui#206]
Add copy to update group target clusters to warn users about clusters that are already targeted won't show up

**Comment by juadk** [comment]
Tested with rancher 2.9.0 / operator 1.6.3 / elemental UI 2.0.0-rc1:

![Image](https://github.com/user-attachments/assets/be7f0451-01cb-4412-8b46-efe71e4869b9)
