### ISSUE TITLE
Use file name from downloadURL instead of elemental.iso

### ISSUE THREAD

**Issue by ldevulder** [rancher/elemental-ui#222]
Current version of the UI plugin defaulted the file name for Elemental OS image to `elemental.iso` or `elemental.img` (for raw image). Latest versions of `elemental-operator` provide a more accurate file name in the `downloadURL` field, so it might be better to use this file name instead.

**Comment by aalves08** [comment]
from which operator version can we get the name from the `downloadURL`?

**Comment by aalves08** [comment]
@juadk @fgiudici @davidcassany  from which version can we get the name from the `downloadURL`?

**Comment by fgiudici** [comment]
> @juadk @fgiudici @davidcassany from which version can we get the name from the `downloadURL`?

Hey Alex! The file name should be present from v1.6.5, which is the current stable (just for info, from this version there will also be the option to download a SHA256 checksum of the iso).
