### ISSUE TITLE
Add copy to Inventory of Machines Selector Template to warn users about machine count

### ISSUE THREAD

**Issue by aalves08** [rancher/elemental-ui#224]
Add some copy to Inventory of Machines Selector Template to warn users about machine count, which must match the number of `Inventory of Machines`, otherwise they won't be bound to the cluster.

Copy to be defined

![Image](https://github.com/user-attachments/assets/66652da5-fe63-4009-805c-11f1ed9fd5ab)

**Comment by aalves08** [comment]
@davidcassany @fgiudici need some help defining the appropriate message 🙏

**Comment by aalves08** [comment]
@davidcassany @fgiudici any feedback please? Thanks

**Comment by fgiudici** [comment]
I don't have strong opinions, could suggest something like:

_Regardless the number of Machine Inventories matching the Selector rules, the number of Machines to be provisioned as part of the Cluster will match  the MachineCount value defined in the MachinePools section._
