### ISSUE TITLE
Allow switching between 'OS image' and 'Manage OS version name' when  creating an 'OS Image Upgrade'

### ISSUE THREAD

**Issue by juadk** [rancher/elemental-ui#3]
**Setup**
- Rancher version: 2.6.8
- Rancher-dashboard branch: elemental-dev

**Describe the bug**

**Context:** Test upgrade in the UI

When we create a new `OS Image Upgrade`, we can only use `OS Image` (osImage) whereas we would like to also use ManagedOSVersion in other cases.
https://rancher.github.io/elemental/upgrade/#selecting-source-for-upgrade

![image](https://user-images.githubusercontent.com/6025636/191459648-b362d9ac-f01f-4b21-a78c-45041ebdfb10.png)

I think we need a dropdown list to select what we want.
Following the warning just below, we don't need to set them at the same time:
`If both osImage and ManagedOSVersion are defined in the same ManagedOSImage be aware that osImage takes precedence.`

**To Reproduce**

1. Setup Rancher and navigate to OS Management.
2. Go to the OS Image Upgrade menu and create a new one

**Comment by kwwii** [comment]
AFAIK there will only be one supported image at any given time. @agracey Is that still correct?

**Comment by kkaempf** [comment]
> AFAIK there will only be one supported image at any given time. @agracey Is that still correct?

Why we wish this to be true, reality is different 😞 

Our "latest" image will only see limited testing, still it needs to run on all kinds of hardware. A SLE update in July/August for example broke booting on specific types of hardware. This is undetectable with the testing means we have.
In cases like this, customers need to have an option to revert to an older image.

The question to @agracey is: How many image versions do we need to support in parallel ?

**Comment by agracey** [comment]
That's a really hard question to answer... 

My (~un~ slightly edited) thoughts:
- We need to discuss migration paths before we really know what versions we need to keep around
- Customers tend to be particular about upgrade timings (for good reasons...)
- I'd rather save too many images than end up not being able to reproduce a customer's set up, maybe we sync old images to some other 3rd party location for "cold storage"? 
- Customers should at least have access to (but not necessarily support for) 
  - The latest tested version of the current stable release
  - The first version of the current stable release
  - The last version of the previous stable release(s)
  - The latest version of the beta/next release
  - The latest build at HEAD
- My concern here is that if keeping images around means keeping and maintaining projects in the build service, this is a ridiculous suggestion...

**Comment by kkaempf** [comment]
If we release via IBS to registry.suse.com, _all_ images will be retained afaik.

**Comment by kwwii** [comment]
Is a list of available images provided by the back-end?

**Comment by kwwii** [comment]
Can we assume that the user wants to:

A) Point to a specific image uri
B) Select from a list of images provided by the backend

**Comment by kwwii** [comment]
Can someone provide clarity on what the Managed OS Versions are?
Can someone provide clarity on what the Managed OS Version Channels are?

What is the difference/similarity and what does the user want or need to do with this? What is the expected workflow(s)

**Comment by aalves08** [comment]
As per commented on Elemental syncs, first iteration of Elemental won't have any OS image selectors nor will tackle with specific UI Managed OS Versions and Managed OS Version Channels.

Bumping out to 2.7.x as this ticket might be relevant in the future. Thanks

FYI @agracey

**Comment by juadk** [comment]
With latest elemental-ui (1.1.0), I can create an upgrade group and choose between OSVersion and OSImage:
![image](https://user-images.githubusercontent.com/6025636/222167957-67e9ae12-ac12-4861-92f6-beca197c21ef.png)
I reported the lower/uppercase issue to Alexandre:
![image](https://user-images.githubusercontent.com/6025636/222168873-6ab55528-1f5b-48ef-bd99-77a466b9c604.png)
Maybe using `Use managed OS version` instead of `Use Managed OS version`, to be consistent with naming.



My cluster was successfully upgraded to dev image:
![image](https://user-images.githubusercontent.com/6025636/222167981-9eefab2c-a8bf-412c-9ab4-b40cda466cb2.png)

I will write a new test to automate that new upgrade path.

**Comment by kkaempf** [comment]
Adding @nunix - jfyi
