### ISSUE TITLE
Can't build on Tumbleweed: @achrinza/node-ipc@9.2.2: The engine "node" is incompatible with this module

### ISSUE THREAD

**Issue by kkaempf** [rancher/elemental-ui#31]
openSUSE Tumbleweed comes with `nodejs 19.0.0` and can't be used to build/install elemental-ui:
```
error @achrinza/node-ipc@9.2.2: The engine "node" is incompatible with this module. Expected version "8 || 10 || 12 || 14 || 16 || 17". Got "19.0.0"
error Found incompatible module.
```

**Comment by kkaempf** [comment]
[@achrinza/node-ipc](https://github.com/achrinza/node-ipc) is at [`10.1.7`](https://github.com/achrinza/node-ipc/releases/tag/v10.1.7) already and has
```
- chore: support Node.js v19 engine
```

**Comment by aalves08** [comment]
It should work on any system you have which has terminal access:
- install [NVM]( https://github.com/nvm-sh/nvm)
- change version to `v14.20.0` -> that's the one that I am using
- yarn install
