### ISSUE TITLE
Small improvements for Elemental UI

### ISSUE THREAD

**Issue by aalves08** [rancher/elemental-ui#32]
1) the dashboard menu item is highlighted when other menu items are selected (dashboard route will probably need to be unique)

2) the edit page for machine registrations needs some UX TLC. Create a dedicated DETAIL (non-edit) page for machine registration with:
- Registration URL
- Download
- Cloud Config

3) Remove YAML Import button/action from Machine Inventory list as it doesn't work for the "blank" cluster concept (which is needed because of RBAC)

**Comment by juadk** [comment]
All good here.


![Image](https://user-images.githubusercontent.com/6025636/202739031-ff19d8c5-f6b8-482a-8371-d84709523c19.png)
