### ISSUE TITLE
Check advanced filtering bug

### ISSUE THREAD

**Issue by aalves08** [rancher/elemental-ui#41]
Check advanced filtering issue that happened on demo

UPDATE:
Cause was related to the "all columns" filtering where codewise we were looking for the search term in labels for items which don't even have a single label there

TO REPRODUCE:
- create two machine inventories
- add a label to one of those items, leave the other without labels
- add a filter "all cols" with any search text

**Comment by aalves08** [comment]
Connected to issue on rancher/dashboard:
https://github.com/rancher/dashboard/issues/7452

**Comment by juadk** [comment]
Built and tested locally, all good!
![image](https://user-images.githubusercontent.com/6025636/202726342-e2cf2515-7141-42a7-8476-9246202e50e9.png)
I created 3 inventories and only one contains the label `test: test1`
After filtering with my label, I can see only one machine inventory:
![image](https://user-images.githubusercontent.com/6025636/202726649-0961caa3-ca6b-4d0e-a99b-082b465cdc53.png)
