### ISSUE TITLE
Link to cluster list filtered by elemental from dashboard

### ISSUE THREAD

**Issue by aalves08** [rancher/elemental-ui#42]
Link to cluster list filtered by elemental from dashboard

**Comment by kwwii** [comment]
Would it be possible to show different buttons depending on whether an elemental cluster already exists?

The "Create Elemental Cluster" button only when the user has NOT created any Elemental clusters?

If the user has existing Elemental clusters, the button would read "Manage Elemental Clusters"

**Comment by aalves08** [comment]
Yes, it's possible. Good idea @kwwii ! Will put that into place 🙏  Thank you for your feedback

**Comment by juadk** [comment]
All good to me!
![Image](https://user-images.githubusercontent.com/6025636/202727613-dfc54f59-e480-4d2c-9e7b-69e442f48b37.png)

And If I click on Manage Elemental Cluster, I only see elemental cluster:


![Image](https://user-images.githubusercontent.com/6025636/202727878-38193da2-f3ba-464f-92e6-bb09eab189b3.png)
