### ISSUE TITLE
Prompt to install elemental-operator when CRDs don't exist

### ISSUE THREAD

**Issue by agracey** [rancher/elemental-ui#43]
If the extension is installed before the elemental-operator, we should be able to see the lack of CRDs and prompt the user to install it. 

This should be a one-click install to install the associated helm chart. Preferably, this helm chart is coming from registry.suse.com (once published there).

**Comment by aalves08** [comment]
Will take a look at this once we are at a point where "one-click" install is possible. Thank you for bringing this up @agracey .

FYI @kwwii
