### ISSUE TITLE
Change "Machine Count" to be number of machines selected

### ISSUE THREAD

**Issue by agracey** [rancher/elemental-ui#44]
When I select some machines in the machine inventory and click "Create Elemental Cluster" from the dropdown, I correctly get pushed over to the cluster creation page. Unless you are paying attention, it's easy to miss that you need to increment the machine count for the machine pool. If you don't do this, you only get a single node cluster.

![image](https://user-images.githubusercontent.com/442274/201419836-5c5dd598-54ed-4410-be58-3178554e723f.png)

**Comment by aalves08** [comment]
@agracey so the number of Machine Counts should match the number of Machine Inventories at all times? If I add 30 mach. inv. it should have 30 machine counts? Just for confirmation, thank you

**Comment by agracey** [comment]
Yes, that is correct.

**Comment by agracey** [comment]
That's a good question. I wonder if anything would break if it was set to 0

**Comment by juadk** [comment]
I just tried with 0 and I can create it:
![image](https://user-images.githubusercontent.com/6025636/202738223-7b509efb-3c86-46ec-a53b-13118d38d169.png)

Then:
![image](https://user-images.githubusercontent.com/6025636/202738423-bded170c-d67a-41a3-97aa-b8726a1fe8bf.png)

**Comment by aalves08** [comment]
@agracey @juadk the default for every other cluster type is 1. I am not knowledgeable on K8s, but does it even make sense to create a cluster with 0 Machine Counts? What if they want to create a cluster with any other purpose?

**Comment by agracey** [comment]
In the general case, there is a use for clusters without nodes as it can be very helpful to keep the control plane for, say, EKS alive but not have any nodes attached. I've done this several times when I didn't want to rebuild everything after a demo but I also didn't want to pay for the cluster to be running.

For our case, I think it might be a bit awkward to have a 0 be allowed but I don't think it makes sense to override the defaults. 

Additionally, the place where I think we need to be careful is that an admin might be setting up clusters (and selectors) before the MachineInventories exists to be included. I don't know what the right UX is for this but my instinct is that most admin's who are doing this type of pre-provisioning would be working with the API as you wouldn't manually go through this process 5000 times.

**Comment by juadk** [comment]
Then, let's close it :smile:
