### ISSUE TITLE
Check issue with advanced filtering disappearing after creating a new Machine Inventory from YAML

### ISSUE THREAD

**Issue by aalves08** [rancher/elemental-ui#45]
- Check issue with advanced filtering controls disappearing (being replaced by simple filtering input) after creating a new Machine Inventory from YAML (route changes after YAML creation -> bug cause)

**QA Testing**
**attention that routes changed from `elemental/c/_/` to `c/_/elemental`. That should impact e2e tests**

**Comment by aalves08** [comment]
UPDATE: cannot reproduce this run it locally for `elemental-ui` repo. Will keep this in backlog until there's a way to accurately reproduce it

**Comment by juadk** [comment]
Not sure to fully understand what the issue was but I tested to create a machine inventory from YAML and all was good with filtering. I even created a label and filtered by it successfully.
