### ISSUE TITLE
Terminology is confusing, let's try to help in the UI

### ISSUE THREAD

**Issue by agracey** [rancher/elemental-ui#46]
I'm sorry that I didn't get this to you earlier. Here are some thoughts on what we could call different sections to be more clear to a user. 

- Machine Registrations -> Registration Endpoints
- Machine Inventories -> Inventory of Machines
- OS Image Updates -> Update Groups (???)
- Managed OS Versions -> OS Versions
- Managed OS Version Channels -> OS Version Channels

Thoughts? 

Screenshot of example changes: 
![image](https://user-images.githubusercontent.com/442274/202058283-68360e09-7000-4bd0-ab34-8a60dabe8ac2.png)

**Comment by agracey** [comment]
I made a typo in the screenshot :(  OS Upgrade Groups should have been OS Update Groups instead

**Comment by aalves08** [comment]
Sounds good to me @agracey . I'll do a run over to update the naming on all places 🙏 

FYI @kwwii

**Comment by juadk** [comment]
Looks good, however, on Andrew's screenshot, we can see `OS Update Groups` whereas on my screenshot, it's only `Update Groups`. 
If it's ok for you @agracey , we can close it.

![image](https://user-images.githubusercontent.com/6025636/203266172-8a9a9e62-5927-4b6b-931e-3e968ae7360c.png)
