### ISSUE TITLE
Tech preview label still showing on cluster creation

### ISSUE THREAD

**Issue by aalves08** [rancher/elemental-ui#49]
- Tech preview label still showing on cluster creation due to elemental extension being installed

FYI @agracey

**Comment by juadk** [comment]
I still see the tech preview label:
![image](https://user-images.githubusercontent.com/6025636/202730294-3d758bf1-62c8-4d55-afcd-60616d561453.png)

**Comment by juadk** [comment]
Looks good with latest fix! Thank you!


![Image](https://user-images.githubusercontent.com/6025636/203260475-4a67615e-8c3f-40ec-908d-9bbffafc9806.png)
