### ISSUE TITLE
Bypassing `Machine Registrations` and creating `Machine Inventories` in OS Management > Machine Inventories allows you to create an Elemental cluster

### ISSUE THREAD

**Issue by markusewalker** [rancher/elemental-ui#5]
**Setup**
- Rancher version: `v2.6.8`
- Browser type & version: Chrome

**Describe the bug**

When navigating to `OS Management`, this is currently the default page that we see:

<img width="1076" alt="image" src="https://user-images.githubusercontent.com/52591819/190689799-9c1b3721-3b19-4d2e-b6cd-047b3caca26a.png">

From how it is structured, you need to first create a machine registration before creating machine inventory. Once those are done, you will be able to create an Elemental cluster. However, you can get around this sequential workflow by simply clicking `Machine Inventories` > `Create From YAML`. 

After you do this, you will now see the following in the OS Management Dashboard:

<img width="1026" alt="image" src="https://user-images.githubusercontent.com/52591819/190690011-f92c7551-c80e-413b-be52-4000937e10cc.png">

From a user standpoint, this seems to be counterintuitive as it is now unclear what I will need to do next. The question we need to ask is `what is the workflow we expect users to perform`? Because as of now, there are two methods in which you can create an Elemental Cluster:

1. Create a machine registration, create a machine inventory, create Elemental cluster
2. Create machine inventory, create machine registration, create Elemental cluster
     - Or even create machine inventory, create Elemental cluster (which is completely incorrect)

**To Reproduce**

1. Setup Rancher and navigate to OS Management > Machine Inventories.
2. Create a new machine inventory.
3. Navigate back to OS Management > Dashboard and note that you are able to create an Elemental cluster.

**Result**
There are multiple methods to create an Elemental cluster rather than a single sequential order to follow.

**Expected Result**
There needs to be a clear method in how users will create an Elemental cluster from Rancher UI; there shouldn't be any guesswork.

**Comment by kwwii** [comment]
The original workflow was to create the Cluster first and then add the Machine Inventories.  I think this needs to work both ways. @agracey Can you confirm?

**Comment by agracey** [comment]
Yes, the only order that should matter is that a Machine Registration is created first. Maybe we should actually add a default entry here as part of the operator helm chart?

After that, we should be able to create the Cluster/SelectorTemplate before or after the target MachineInventory's exist. 

The reason for this is that a user may want to set up all of the clusters for each location ahead of time then allow those clusters to provision as the hardware is shipped and turned on. Or a customer might want to have more control over provisioning and use some higher level automation.

**Comment by agracey** [comment]
Just added this: https://github.com/rancher/elemental/issues/407

**Comment by aalves08** [comment]
Will close this issue as dashboard will be re-designed and a new implementation without theses steps will come soon. Thanks
