### ISSUE TITLE
Relax coupling between extension and main Rancher application

### ISSUE THREAD

**Issue by agracey** [rancher/elemental-ui#50]
Based on https://github.com/rancher/dashboard/issues/7485.

It seems awkward that we are pulling in an old version of the UI instead of "late binding" against what Rancher is loading.

**Comment by juadk** [comment]
No more conflict between extensions:
I installed all available extensions and I was able to provision an Elemental cluster.
![image.png](https://zube.io/files/rancher/46ba5d2340a9f5ed4bb8929ab262ae49-image.png)
