### ISSUE TITLE
Fix issue with cluster explorer dashboard being overridden by Elemental dashboard view

### ISSUE THREAD

**Issue by aalves08** [rancher/elemental-ui#59]
- Fix issue with cluster explorer dashboard being overridden by Elemental dashboard view

![Screenshot 2022-11-24 at 15.47.29.png](https://zube.io/files/rancher/36b01490bf9438cdb2a24363ffe4e5c0-screenshot-2022-11-24-at-15-47-29.png)

**To reproduce**
- Go to OS management to load Elemental dashboard view
- Go to your local Cluster on the side-menu (so that it loads the cluster explorer view)
- Check that cluster explorer dashboard being overridden by Elemental dashboard view

**Comment by juadk** [comment]
All good to me https://github.com/rancher/elemental/pull/542
