### ISSUE TITLE
Elemental - Add a form to create Machine inventory labels and annotations when you create a machine registration

### ISSUE THREAD

**Issue by juadk** [rancher/elemental-ui#6]
**Setup**
- Rancher version: 2.6.7
- Rancher-dashboard branch: elemental-dev

**Describe the bug**
In the machine registration screen, it might be a good idea to add fields to create `machineInventoryLabels` and `machineInventoryAnnotations`

![image](https://user-images.githubusercontent.com/6025636/190201707-6f78f3ab-9ebe-4b4f-bad1-1926c5e7ef58.png)

**Comment by kwwii** [comment]
This should be a feature request which is defined by PM. In any case, it is not a bug.

**Comment by agracey** [comment]
@kwwii Where should I put requests like this? I do think this is a good request and would make our customer's life easier.
