### ISSUE TITLE
Capitalise title of extension in card on Extensions screen

### ISSUE THREAD

**Issue by aalves08** [rancher/elemental-ui#61]
- Capitalise title of extension in card on Extensions screen (ex: elemental vs Elemental)

All titles are currently in lowercase
![Screenshot 2023-02-06 at 17.16.59.png](https://zube.io/files/rancher/682fd3244893341a50c75aeef2e15c26-screenshot-2023-02-06-at-17-16-59.png)

**Comment by aalves08** [comment]
PR here: https://github.com/rancher/dashboard/pull/7709

**Comment by juadk** [comment]
All good! 
![image.png](https://zube.io/files/rancher/c2ff55846ce470bce91e37336f51eafc-image.png)
