### ISSUE TITLE
Dashboard link redirect to welcome page with a user granted with elemental-admin role

### ISSUE THREAD

**Issue by juadk** [rancher/elemental-ui#64]
This issue has been spotted by our automated test. I will join Cypress record.

The test uses a standard user with the elemental-administrator role:
![image](https://user-images.githubusercontent.com/6025636/204927085-e9303e9a-f5f3-420b-b7cb-8eb62566204c.png)

I can create machine registration and cluster but once a cluster is deployed, if I click on the dashboard link in the OS management , I'm redirected to the welcome page instead of the global overview of my resources:
![image](https://user-images.githubusercontent.com/6025636/204927460-b072e1d9-844b-4df9-8f55-ea7cd771db98.png)

Weird thing is that I can browse the other menus without issue:
![image](https://user-images.githubusercontent.com/6025636/204927566-41d5afd1-16f9-4c5a-92a2-8d387b90d7fa.png)

And **important thing** is if I remove the cluster, I can see the dashboard as expected so something is happening when a cluster exists.

![image](https://user-images.githubusercontent.com/6025636/204929321-8c67587e-c1a2-4a3e-aac3-817483bb8d5e.png)

## Env:
Rancher: `2.7.0-rc12`
Elemental-extension: `1.0.0`

## How to reproduce
It was spotted by automated test but I was able to reproduce it manually.

- Create a new user with elemental-administrator role
- Login in with the new user
- Create machine registration
- Boot a node
- Create downstream cluster
- Click on the dashboard item in the OS management menu

## Cypress video
https://user-images.githubusercontent.com/6025636/204928137-678830ed-0802-439d-b52a-9948fde46f97.mp4

The issue happens at 2.24.

**Comment by aalves08** [comment]
@juadk just tested with elemental-head and I cannot see any issues with it.

I don't have the way to boot a node correctly, but creating a machine reg + creating an elemental cluster with a standard user + clicking on OS management takes me to the correct screen.

I haven't introduced any changes, afaik, on head that would impact this, so you might be able to test with `1.0.1`.

**Comment by juadk** [comment]
I just triggered a [test](https://github.com/rancher/elemental/actions/runs/4281159405/jobs/7453854022) using a branch where I removed the workaround https://github.com/rancher/elemental/commit/946bd088e1f404542ac84a335980e7f9bd5118ab

**Comment by juadk** [comment]
I quickly tested it manually and it still happens.
I can see the cluster in Cluster Management:
![image](https://user-images.githubusercontent.com/6025636/221539038-5f0927aa-b720-4e06-a76e-bce650f9579e.png)

But if I check the Elemental Dashboard:
![image](https://user-images.githubusercontent.com/6025636/221539202-da33362e-a66a-4f3a-a528-8a828b05115c.png)
