### ISSUE TITLE
update elemental extension icon

### ISSUE THREAD

**Issue by aalves08** [rancher/elemental-ui#66]
update elemental extension icon - can only be added after 2.7.1 is released
https://rancher.github.io/icons/

![Screenshot 2022-12-14 at 17.00.30.png](https://zube.io/files/rancher/89d1b4eca1c2afe36a743a49ec1e1d0c-screenshot-2022-12-14-at-17-00-30.png)

**Comment by juadk** [comment]
All good, Cypress code updated to handle the new icon https://github.com/rancher/elemental/pull/702
![image](https://user-images.githubusercontent.com/6025636/222147793-64864d0d-6484-4acc-89f5-6d4276934af1.png)
