### ISSUE TITLE
Issue with proxy configuration for elemental/download route

### ISSUE THREAD

**Issue by aalves08** [rancher/elemental-ui#67]
There's an issue with proxy configuration for `elemental/download` route on elemental `v1.0.0`, which prevents the correct download of the registration YAML. It can be downloaded, but the content is gibberish.

Let's try to release a new shell version, update it on elemental and check if it fixes the problem

**Comment by juadk** [comment]
With rancher 2.7.2-rc2 and elemental-ui 1.0.1, I was able to download the registration file and the content is fine.
