### ISSUE TITLE
Check problem with advanced filtering + names with special chars and uppercase

### ISSUE THREAD

**Issue by aalves08** [rancher/elemental-ui#68]
Check problem with advanced filtering + names with special chars and uppercase

Ex: label with a value AuthenticAMD

**Comment by aalves08** [comment]
PR here:
https://github.com/rancher/dashboard/pull/8055

**Comment by juadk** [comment]
Create label with uppercase:
![image.png](https://zube.io/files/rancher/1dbb452511108285174e472f394f8eff-image.png)

Filtering test:
![image.png](https://zube.io/files/rancher/2e60a3cd5690d7bbdc31f2056fd191c0-image.png)

All works as expected
