### ISSUE TITLE
Prevent user to create label greater than 63 characters for Machine Inv. on Reg. Endpoint

### ISSUE THREAD

**Issue by juadk** [rancher/elemental-ui#77]
## Bug description
UI allows to create label greater than 63 characters, because if you create such a label, elemental node will fail to boot:

![image](https://user-images.githubusercontent.com/6025636/219007682-ef8c84e0-9c24-4f93-a12e-328a45a23fa0.png)

## Env
Rancher: `2.7.2-rc2`
Elemental-UI: `1.0.1`

## Expected behavior
UI should not allow user to enter label greater than 63.

**Comment by nwmac** [comment]
@aalves08 https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/ - worth noting that the `name` part is limited to 63 chars - the `prefix` can be 253 chars in length.

**Comment by cnotv** [comment]
@aalves08 You can use the existing validation in the [rke2 editor](https://github.com/rancher/dashboard/blob/master/shell/edit/provisioning.cattle.io.cluster/rke2.vue#L311). Then you can add dynamically the [between rule](https://github.com/rancher/dashboard/blob/master/shell/utils/validators/formRules/index.ts#L80) I used already for the  [password setting](https://github.com/rancher/dashboard/issues/6633) to the `fvFormRuleSets` as [I did there](https://github.com/rancher/dashboard/blob/master/shell/edit/management.cattle.io.setting.vue#L47).

**Comment by juadk** [comment]
> @aalves08 https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/ - worth noting that the `name` part is limited to 63 chars - the `prefix` can be 253 chars in length.

Indeed, just tested it with a long prefix and name ( < 63 ), total was 71 characters and it worked as expected.

**Comment by juadk** [comment]
Sucessfully tested in latest elemental-ui version (1.1.0)
![image](https://user-images.githubusercontent.com/6025636/222170380-17642972-0e3f-4594-9ae1-bc28292ffcc4.png)

We can see the warning and the Create button becomes un-clickable.
I will add a regression test in our automated test suite.
