### ISSUE TITLE
Create UI interface for OS Version Channels

### ISSUE THREAD

**Issue by aalves08** [rancher/elemental-ui#81]
Create UI interface for OS Version Channels

**Comment by juadk** [comment]
I was able to create OS Version Channels:
![image](https://user-images.githubusercontent.com/6025636/222164027-f79b3fe0-3a09-4a1d-9335-fef5b8b64a29.png)

And then, we can OS versions which come from my channel `mychannel`:
![image](https://user-images.githubusercontent.com/6025636/222164398-5a06f60d-8553-4a38-9de6-50abe5a60da6.png)

Issue can be closed, I will add a new automated test to test that upgrade path.
