### ISSUE TITLE
e2e ui: machine registration appears twice

### ISSUE THREAD

**Issue by juadk** [rancher/elemental-ui#87]
Follow-up of https://github.com/rancher/elemental/issues/714

![image](https://user-images.githubusercontent.com/6025636/223656457-ad4135de-d3f3-403e-98c8-906bc99229fa.png)

Of course, it happens sporadically and only in the CI with our automation, I cannot reproduce it manually...
```
Rancher version: 2.7.1
Elemental ui: 1.0.0
```
As discussed with @aalves08 , nobody will work on that now, it's not a blocker.

**Comment by kkaempf** [comment]
Not reproducible
